// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPJ2XFa78q5seESB871tgtOZWsMtZJeG8',
    appId: '1:58354910611:web:a577af7152cb9aafe49466',
    messagingSenderId: '58354910611',
    projectId: 'seribujasa-7eabe',
    authDomain: 'seribujasa-7eabe.firebaseapp.com',
    storageBucket: 'seribujasa-7eabe.appspot.com',
    measurementId: 'G-2Y72KW76Q2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuezJnBe6KGAMxSlGzj_iw2JUnypZ1qHE',
    appId: '1:58354910611:android:21453b200314a6e4e49466',
    messagingSenderId: '58354910611',
    projectId: 'seribujasa-7eabe',
    storageBucket: 'seribujasa-7eabe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOW2bLp1YvMuEoZ5ovEVbMWX__wOqfsLY',
    appId: '1:58354910611:ios:4d2ebbdf898d2391e49466',
    messagingSenderId: '58354910611',
    projectId: 'seribujasa-7eabe',
    storageBucket: 'seribujasa-7eabe.appspot.com',
    iosClientId: '58354910611-4kci0huegckmpbvn0jrg6t2eg0prifik.apps.googleusercontent.com',
    iosBundleId: 'com.qixerios.app',
  );
}
